import type { Alert, Asset } from "./types";

// Timestamps are relative to server start so the demo always looks recent.
const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();

export const assets: Asset[] = [
  {
    id: "ast-01",
    name: "web-prod-01",
    type: "server",
    ip: "10.0.1.12",
    owner: "Platform",
    riskScore: 91,
    lastSeen: minutesAgo(2),
  },
  {
    id: "ast-02",
    name: "web-prod-02",
    type: "server",
    ip: "10.0.1.13",
    owner: "Platform",
    riskScore: 64,
    lastSeen: minutesAgo(3),
  },
  {
    id: "ast-03",
    name: "db-customers",
    type: "database",
    ip: "10.0.2.5",
    owner: "Data",
    riskScore: 78,
    lastSeen: minutesAgo(1),
  },
  {
    id: "ast-04",
    name: "db-analytics",
    type: "database",
    ip: "10.0.2.9",
    owner: "Data",
    riskScore: 35,
    lastSeen: minutesAgo(15),
  },
  {
    id: "ast-05",
    name: "shop.example.com",
    type: "domain",
    ip: null,
    owner: "Marketing",
    riskScore: 57,
    lastSeen: minutesAgo(30),
  },
  {
    id: "ast-06",
    name: "vpn.example.com",
    type: "domain",
    ip: null,
    owner: "IT",
    riskScore: 83,
    lastSeen: minutesAgo(8),
  },
  {
    id: "ast-07",
    name: "laptop-finance-04",
    type: "workstation",
    ip: "192.168.10.44",
    owner: "Finance",
    riskScore: 72,
    lastSeen: minutesAgo(45),
  },
  {
    id: "ast-08",
    name: "laptop-dev-11",
    type: "workstation",
    ip: "192.168.10.71",
    owner: "Engineering",
    riskScore: 22,
    lastSeen: minutesAgo(5),
  },
  {
    id: "ast-09",
    name: "s3-backups",
    type: "cloud",
    ip: null,
    owner: "Platform",
    riskScore: 88,
    lastSeen: minutesAgo(12),
  },
  {
    id: "ast-10",
    name: "k8s-cluster-eu",
    type: "cloud",
    ip: null,
    owner: "Platform",
    riskScore: 41,
    lastSeen: minutesAgo(4),
  },
  {
    id: "ast-11",
    name: "mail-gateway",
    type: "server",
    ip: "10.0.3.2",
    owner: "IT",
    riskScore: 50,
    lastSeen: minutesAgo(6),
  },
  {
    id: "ast-12",
    name: "laptop-hr-02",
    type: "workstation",
    ip: "192.168.10.23",
    owner: "HR",
    riskScore: 12,
    lastSeen: minutesAgo(240),
  },
];

export const alerts: Alert[] = [
  {
    id: "alr-001",
    title: "Brute-force login attempts",
    description: "312 failed SSH logins from 3 IPs in 10 minutes.",
    severity: "critical",
    status: "open",
    assetId: "ast-01",
    source: "IDS",
    createdAt: minutesAgo(4),
  },
  {
    id: "alr-002",
    title: "Public bucket detected",
    description: "Bucket policy allows anonymous read access.",
    severity: "critical",
    status: "investigating",
    assetId: "ast-09",
    source: "Cloud scanner",
    createdAt: minutesAgo(26),
  },
  {
    id: "alr-003",
    title: "Outdated TLS version",
    description: "Endpoint still accepts TLS 1.0 connections.",
    severity: "high",
    status: "open",
    assetId: "ast-06",
    source: "Vulnerability scan",
    createdAt: minutesAgo(48),
  },
  {
    id: "alr-004",
    title: "SQL injection pattern",
    description: "WAF blocked 17 requests matching SQLi signatures.",
    severity: "high",
    status: "open",
    assetId: "ast-03",
    source: "WAF",
    createdAt: minutesAgo(65),
  },
  {
    id: "alr-005",
    title: "Malware signature match",
    description: "Endpoint agent quarantined a suspicious executable.",
    severity: "high",
    status: "investigating",
    assetId: "ast-07",
    source: "EDR",
    createdAt: minutesAgo(90),
  },
  {
    id: "alr-006",
    title: "Certificate expires soon",
    description: "TLS certificate expires in 9 days.",
    severity: "medium",
    status: "open",
    assetId: "ast-05",
    source: "Certificate monitor",
    createdAt: minutesAgo(130),
  },
  {
    id: "alr-007",
    title: "Unusual outbound traffic",
    description: "Traffic to an unknown ASN 4x above baseline.",
    severity: "medium",
    status: "open",
    assetId: "ast-02",
    source: "NDR",
    createdAt: minutesAgo(180),
  },
  {
    id: "alr-008",
    title: "Admin login from new country",
    description: "Successful admin login from a never-seen location.",
    severity: "high",
    status: "resolved",
    assetId: "ast-11",
    source: "IAM",
    createdAt: minutesAgo(300),
  },
  {
    id: "alr-009",
    title: "Missing security patches",
    description: "4 critical OS patches pending for more than 30 days.",
    severity: "medium",
    status: "open",
    assetId: "ast-10",
    source: "Patch manager",
    createdAt: minutesAgo(420),
  },
  {
    id: "alr-010",
    title: "Disk encryption disabled",
    description: "BitLocker is turned off on this device.",
    severity: "medium",
    status: "investigating",
    assetId: "ast-07",
    source: "MDM",
    createdAt: minutesAgo(600),
  },
  {
    id: "alr-011",
    title: "Weak password policy",
    description: "Database user accounts allow 6-character passwords.",
    severity: "low",
    status: "open",
    assetId: "ast-04",
    source: "Config audit",
    createdAt: minutesAgo(900),
  },
  {
    id: "alr-012",
    title: "SPF record too permissive",
    description: "SPF record ends with +all.",
    severity: "low",
    status: "resolved",
    assetId: "ast-05",
    source: "DNS audit",
    createdAt: minutesAgo(1500),
  },
  {
    id: "alr-013",
    title: "Port scan detected",
    description: "Sequential scan of 1,024 ports from an external IP.",
    severity: "low",
    status: "resolved",
    assetId: "ast-01",
    source: "IDS",
    createdAt: minutesAgo(2000),
  },
  {
    id: "alr-014",
    title: "Privilege escalation attempt",
    description: "User tried to add themselves to the Domain Admins group.",
    severity: "critical",
    status: "open",
    assetId: "ast-08",
    source: "IAM",
    createdAt: minutesAgo(12),
  },
];
